name 'chef_portal'
maintainer 'George Miranda (<gmiranda@chef.io>)'
maintainer_email 'gmiranda@chef.io'
license 'mit'
description 'Installs/Configures chef_portal'
long_description 'Installs/Configures chef_portal'
version '0.1.0'

supports 'centos'
supports 'amazon'

depends 'chef-dk'
depends 'sudo'
depends 'chef_classroom'
depends 'guacamole'
